version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=wowlogbook
      - DB_USERNAME=wowuser
      - DB_PASSWORD=wowpass
      - APP_ENV=local
    depends_on:
      - db

  db:
    image: mariadb:11.3
    restart: always
    environment:
      MARIADB_DATABASE: wowlogbook
      MARIADB_USER: wowuser
      MARIADB_PASSWORD: wowpass
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3300:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
